version: '3'

services:
  mongodb:
    image: mongo:3.6
    ports:
      - 27017:27017
  neo4j:
    image: neo4j:3.3
  app:
    build: .
    volumes:
      - './backend:/app'
    command: python server.py
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - neo4j
